# Generated by Django 4.2.7 on 2023-12-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='team1_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Время команды 1'),
        ),
        migrations.AddField(
            model_name='race',
            name='team2_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Время команды 2'),
        ),
        migrations.AddField(
            model_name='race',
            name='team3_time',
            field=models.DurationField(blank=True, null=True, verbose_name='Время команды 3'),
        ),
    ]
