# Generated by Django 4.2.7 on 2023-12-11 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_race_team1_time_race_team2_time_race_team3_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='team1_time',
        ),
        migrations.RemoveField(
            model_name='race',
            name='team2_time',
        ),
        migrations.RemoveField(
            model_name='race',
            name='team3_time',
        ),
        migrations.AddField(
            model_name='race',
            name='second_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_place', to='races.team', verbose_name='Второе место'),
        ),
        migrations.AddField(
            model_name='race',
            name='third_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_place', to='races.team', verbose_name='Третье место'),
        ),
        migrations.AlterField(
            model_name='race',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='races.team', verbose_name='Победитель'),
        ),
    ]
