# Generated by Django 4.2.7 on 2023-12-11 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_remove_race_team1_time_remove_race_team2_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='second_place',
        ),
        migrations.RemoveField(
            model_name='race',
            name='third_place',
        ),
        migrations.AlterField(
            model_name='race',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='races.team', verbose_name='Победитель'),
        ),
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken', models.DurationField(verbose_name='Время прохождения')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.race', verbose_name='Гонка')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Результат гонки',
                'verbose_name_plural': 'Результаты гонок',
            },
        ),
    ]
